# Generated by Django 5.0.1 on 2024-01-23 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('paymentMethod', models.CharField(blank=True, max_length=50, null=True)),
                ('delieveryCharge', models.DecimalField(decimal_places=2, max_digits=5)),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=9)),
                ('isPaid', models.BooleanField(default=False)),
                ('isDelivered', models.BooleanField(default=False)),
                ('deliveredTime', models.DateTimeField(auto_now_add=True)),
                ('orderedTime', models.DateTimeField(auto_now_add=True)),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('camera', models.CharField(blank=True, max_length=100)),
                ('processor', models.CharField(blank=True, max_length=100)),
                ('display', models.TextField(blank=True, max_length=1000)),
                ('rating', models.CharField(max_length=50)),
                ('features', models.TextField(blank=True, max_length=100, null=True)),
                ('numReviews', models.IntegerField(blank=True, default=0, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('countStock', models.IntegerField(blank=True, default=0, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.product')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.IntegerField(blank=True, default=0, null=True)),
                ('comment', models.TextField(blank=True, max_length=1000, null=True)),
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('shippingPrice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('address', models.TextField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('postalcode', models.IntegerField(default=1100)),
                ('country', models.CharField(max_length=50)),
                ('order', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.order')),
            ],
        ),
    ]
