const products = [
  {
    '_id': '1',
    'name': 'TCL 408 Smartphone',
    'image': '/images/TCL-408.jpg',
    'Model': '408',
    'Display': '6.6" HD+, V-Notch, IPS LCD Display',
    'Processor': 'Mediatek MT6762G Helio ',
    'Camera': 'Triple 50+2 MP on Rear, 8MP Selfie',
    'Features': 'Side Fingerprint, 10W Fast Charging',
    'Price':'50000৳',
    'countInStock': 10,
    'numReview':'1',
    'rating':'1',
  },
  {
    '_id': '2',
    'name': 'Vivo Y02A Smartphone',
    'image': '/images/Vivo-Y02A.jpg',
    'Display': '6.51" HD+ Eye Protection Screen',
    'Processor': 'Mediatek MT6765 Helio ',
    'Camera': 'Single 8MP on Rear, 5MP Front',
    'Features': '5000mAh Battery',
    'Price':'26000৳',
    'countInStock': 10,
    'numReview':'4',
    'rating':'1',
  },
  {
    '_id': '3',
    'name': 'Realme C30s Smartphone',
    'image': '/images/Realme-C30s.jpg',
    'Display': '6.5" HD+ Display',
    'Processor': 'Unisoc SC9863A (28 nm)',
    'Camera': 'Single 8MP Rear, 5MP Front',
    'Features': '5000mAh Battery',
    'Price':'24000৳',
    'countInStock': 10,
    'numReview':'4',
    'rating':'1',
  },
  {
    '_id': '4',
    'name': 'Samsung Galaxy A03 Core',
    'image': '/images/Samsung-Galaxy-A03.jpg',
    'Display': '6.5" 720 x 1600 (HD+)',
    'Processor': 'Octa-core (1.6GHz,1.2GHz)',
    'Camera': '8MP Rear, 5MP Front',
    'Features': '5000mAh Li-Ion Battery',
    'Price':'32000৳',
    'countInStock': 10,
    'numReview':'4',
    'rating':'5',
  },
  {
    '_id': '5',
    'name': 'Vivo Y02t Smartphone',
    'image': '/images/Vivo-Y02t.jpg',
    'Display': '6.51" HD+ Eye Protection Screen',
    'Processor': 'Mediatek MT6765 Helio ',
    'Camera': 'Single 8MP on Rear, 5MP Front',
    'Features': '5000mAh Battery, 4GB Extended RAM',
    'Price':'50000৳',
    'countInStock': 10,
    'numReview':'4',
    'rating':'4',
  },
  {
    '_id': '6',
    'name': 'OPPO A17k Smartphone ',
    'image': '/images/OPPO-A17k.jpg',
    'Display': '6.56" HD+ Eye-care Display',
    'Processor': 'Mediatek MT6765 Helio  ',
    'Camera': 'Single 8MP on Rear, 5MP Front',
    'Features': 'Side-mounted Fingerprint, IPX4',
    'Price':'25000৳',
    'numReview':'4',
    'countInStock': 0,
    'rating':'3',
  },
  {
    '_id': '7',
    'name': 'OPPO A18 Smartphone',
    'image': '/images/OPPO-A18.jpg',
    'Display': '6.56" HD+ 90Hz Colour-Rich Display',
    'Processor': 'MediaTek Helio G85',
    'Camera': 'Dual 8+2 MP on Rear, 5MP Front',
    'Features': 'IP54, Side Fingerprint, 18W Fast Charging',
    'Price':'35000৳',
    'countInStock': 10,
    'numReview':'4',
    'rating':'4',
  },
  {
    '_id': '8',
    'name': 'Vivo Y02t Smartphone',
    'image': '/images/Vivo-Y02.jpg',
    'Display': '6.51" HD+ Eye Protection Screen',
    'Processor': 'Mediatek MT6765 Helio ',
    'Camera': 'Single 8MP on Rear, 5MP Front',
    'Features': '5000mAh Battery',
    'Price':'20000৳',
    'countInStock': 10,
    'numReview':'4',
    'rating':'5',
  },
]


export default products
